"""Países y provincias argentinas para el formulario de organización."""

from __future__ import annotations

# Lista en español (nombres habituales). Argentina primero por uso local del producto.
PAISES: list[str] = [
    "Argentina",
    "Bolivia",
    "Brasil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Ecuador",
    "El Salvador",
    "España",
    "Estados Unidos",
    "Guatemala",
    "Honduras",
    "México",
    "Nicaragua",
    "Panamá",
    "Paraguay",
    "Perú",
    "Portugal",
    "Puerto Rico",
    "República Dominicana",
    "Uruguay",
    "Venezuela",
    "Alemania",
    "Andorra",
    "Angola",
    "Arabia Saudita",
    "Argelia",
    "Australia",
    "Austria",
    "Bélgica",
    "Belice",
    "Canadá",
    "China",
    "Corea del Sur",
    "Croacia",
    "Dinamarca",
    "Egipto",
    "Emiratos Árabes Unidos",
    "Eslovaquia",
    "Eslovenia",
    "Estonia",
    "Filipinas",
    "Finlandia",
    "Francia",
    "Grecia",
    "Hungría",
    "India",
    "Indonesia",
    "Irlanda",
    "Islandia",
    "Israel",
    "Italia",
    "Japón",
    "Kenia",
    "Letonia",
    "Lituania",
    "Luxemburgo",
    "Malasia",
    "Marruecos",
    "Nigeria",
    "Noruega",
    "Nueva Zelanda",
    "Países Bajos",
    "Polonia",
    "Reino Unido",
    "República Checa",
    "Rumania",
    "Rusia",
    "Senegal",
    "Singapur",
    "Sudáfrica",
    "Suecia",
    "Suiza",
    "Tailandia",
    "Turquía",
    "Ucrania",
    "Vietnam",
    "Otro",
]

PROVINCIAS_ARGENTINA: list[str] = [
    "Buenos Aires",
    "CABA",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
]


def region_label(pais: str, provincia: str = "") -> str:
    """Texto unificado para export / compatibilidad con campo region."""
    pais = (pais or "").strip()
    provincia = (provincia or "").strip()
    if pais == "Argentina" and provincia:
        return f"Argentina · {provincia}"
    return pais
