[theme]
primaryColor = "#044A30"
backgroundColor = "#D5E9E2"
secondaryBackgroundColor = "#C6E0D6"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
